/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

goog.exportSymbol('proto.Ip_info', null, global);
goog.exportSymbol('proto.enum_root_server', null, global);
goog.exportSymbol('proto.enum_root_type', null, global);
goog.exportSymbol('proto.enum_server_method', null, global);
goog.exportSymbol('proto.ext_key_info', null, global);
goog.exportSymbol('proto.msg_header', null, global);
goog.exportSymbol('proto.root', null, global);
goog.exportSymbol('proto.user_info', null, global);

/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.msg_header = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.msg_header, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.msg_header.displayName = 'proto.msg_header';
}


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.msg_header.prototype.toObject = function(opt_includeInstance) {
  return proto.msg_header.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.msg_header} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.msg_header.toObject = function(includeInstance, msg) {
  var f, obj = {
    type: jspb.Message.getFieldWithDefault(msg, 1, 0),
    server: jspb.Message.getFieldWithDefault(msg, 2, 0),
    method: jspb.Message.getFieldWithDefault(msg, 3, 0),
    uid: jspb.Message.getFieldWithDefault(msg, 4, 0),
    autoToken: jspb.Message.getFieldWithDefault(msg, 5, 0),
    seq: jspb.Message.getFieldWithDefault(msg, 6, 0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.msg_header}
 */
proto.msg_header.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.msg_header;
  return proto.msg_header.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.msg_header} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.msg_header}
 */
proto.msg_header.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {!proto.enum_root_type} */ (reader.readEnum());
      msg.setType(value);
      break;
    case 2:
      var value = /** @type {!proto.enum_root_server} */ (reader.readEnum());
      msg.setServer(value);
      break;
    case 3:
      var value = /** @type {!proto.enum_server_method} */ (reader.readEnum());
      msg.setMethod(value);
      break;
    case 4:
      var value = /** @type {number} */ (reader.readUint32());
      msg.setUid(value);
      break;
    case 5:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setAutoToken(value);
      break;
    case 6:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setSeq(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.msg_header.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.msg_header.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.msg_header} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.msg_header.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getType();
  if (f !== 0.0) {
    writer.writeEnum(
      1,
      f
    );
  }
  f = message.getServer();
  if (f !== 0.0) {
    writer.writeEnum(
      2,
      f
    );
  }
  f = message.getMethod();
  if (f !== 0.0) {
    writer.writeEnum(
      3,
      f
    );
  }
  f = message.getUid();
  if (f !== 0) {
    writer.writeUint32(
      4,
      f
    );
  }
  f = message.getAutoToken();
  if (f !== 0) {
    writer.writeInt32(
      5,
      f
    );
  }
  f = message.getSeq();
  if (f !== 0) {
    writer.writeInt32(
      6,
      f
    );
  }
};


/**
 * optional enum_root_type type = 1;
 * @return {!proto.enum_root_type}
 */
proto.msg_header.prototype.getType = function() {
  return /** @type {!proto.enum_root_type} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/** @param {!proto.enum_root_type} value */
proto.msg_header.prototype.setType = function(value) {
  jspb.Message.setProto3EnumField(this, 1, value);
};


/**
 * optional enum_root_server server = 2;
 * @return {!proto.enum_root_server}
 */
proto.msg_header.prototype.getServer = function() {
  return /** @type {!proto.enum_root_server} */ (jspb.Message.getFieldWithDefault(this, 2, 0));
};


/** @param {!proto.enum_root_server} value */
proto.msg_header.prototype.setServer = function(value) {
  jspb.Message.setProto3EnumField(this, 2, value);
};


/**
 * optional enum_server_method method = 3;
 * @return {!proto.enum_server_method}
 */
proto.msg_header.prototype.getMethod = function() {
  return /** @type {!proto.enum_server_method} */ (jspb.Message.getFieldWithDefault(this, 3, 0));
};


/** @param {!proto.enum_server_method} value */
proto.msg_header.prototype.setMethod = function(value) {
  jspb.Message.setProto3EnumField(this, 3, value);
};


/**
 * optional uint32 uid = 4;
 * @return {number}
 */
proto.msg_header.prototype.getUid = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 4, 0));
};


/** @param {number} value */
proto.msg_header.prototype.setUid = function(value) {
  jspb.Message.setProto3IntField(this, 4, value);
};


/**
 * optional int32 auto_token = 5;
 * @return {number}
 */
proto.msg_header.prototype.getAutoToken = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 5, 0));
};


/** @param {number} value */
proto.msg_header.prototype.setAutoToken = function(value) {
  jspb.Message.setProto3IntField(this, 5, value);
};


/**
 * optional int32 seq = 6;
 * @return {number}
 */
proto.msg_header.prototype.getSeq = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 6, 0));
};


/** @param {number} value */
proto.msg_header.prototype.setSeq = function(value) {
  jspb.Message.setProto3IntField(this, 6, value);
};



/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.ext_key_info = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.ext_key_info, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.ext_key_info.displayName = 'proto.ext_key_info';
}


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.ext_key_info.prototype.toObject = function(opt_includeInstance) {
  return proto.ext_key_info.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.ext_key_info} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.ext_key_info.toObject = function(includeInstance, msg) {
  var f, obj = {
    key: jspb.Message.getFieldWithDefault(msg, 1, ""),
    value: jspb.Message.getFieldWithDefault(msg, 2, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.ext_key_info}
 */
proto.ext_key_info.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.ext_key_info;
  return proto.ext_key_info.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.ext_key_info} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.ext_key_info}
 */
proto.ext_key_info.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setKey(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setValue(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.ext_key_info.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.ext_key_info.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.ext_key_info} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.ext_key_info.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getKey();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getValue();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
};


/**
 * optional string key = 1;
 * @return {string}
 */
proto.ext_key_info.prototype.getKey = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/** @param {string} value */
proto.ext_key_info.prototype.setKey = function(value) {
  jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional string value = 2;
 * @return {string}
 */
proto.ext_key_info.prototype.getValue = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/** @param {string} value */
proto.ext_key_info.prototype.setValue = function(value) {
  jspb.Message.setProto3StringField(this, 2, value);
};



/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.root = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.root, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.root.displayName = 'proto.root';
}


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.root.prototype.toObject = function(opt_includeInstance) {
  return proto.root.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.root} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.root.toObject = function(includeInstance, msg) {
  var f, obj = {
    header: (f = msg.getHeader()) && proto.msg_header.toObject(includeInstance, f),
    body: msg.getBody_asB64(),
    ext: (f = msg.getExt()) && proto.ext_key_info.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.root}
 */
proto.root.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.root;
  return proto.root.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.root} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.root}
 */
proto.root.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.msg_header;
      reader.readMessage(value,proto.msg_header.deserializeBinaryFromReader);
      msg.setHeader(value);
      break;
    case 2:
      var value = /** @type {!Uint8Array} */ (reader.readBytes());
      msg.setBody(value);
      break;
    case 3:
      var value = new proto.ext_key_info;
      reader.readMessage(value,proto.ext_key_info.deserializeBinaryFromReader);
      msg.setExt(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.root.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.root.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.root} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.root.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getHeader();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      proto.msg_header.serializeBinaryToWriter
    );
  }
  f = message.getBody_asU8();
  if (f.length > 0) {
    writer.writeBytes(
      2,
      f
    );
  }
  f = message.getExt();
  if (f != null) {
    writer.writeMessage(
      3,
      f,
      proto.ext_key_info.serializeBinaryToWriter
    );
  }
};


/**
 * optional msg_header header = 1;
 * @return {?proto.msg_header}
 */
proto.root.prototype.getHeader = function() {
  return /** @type{?proto.msg_header} */ (
    jspb.Message.getWrapperField(this, proto.msg_header, 1));
};


/** @param {?proto.msg_header|undefined} value */
proto.root.prototype.setHeader = function(value) {
  jspb.Message.setWrapperField(this, 1, value);
};


proto.root.prototype.clearHeader = function() {
  this.setHeader(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.root.prototype.hasHeader = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional bytes body = 2;
 * @return {!(string|Uint8Array)}
 */
proto.root.prototype.getBody = function() {
  return /** @type {!(string|Uint8Array)} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * optional bytes body = 2;
 * This is a type-conversion wrapper around `getBody()`
 * @return {string}
 */
proto.root.prototype.getBody_asB64 = function() {
  return /** @type {string} */ (jspb.Message.bytesAsB64(
      this.getBody()));
};


/**
 * optional bytes body = 2;
 * Note that Uint8Array is not supported on all browsers.
 * @see http://caniuse.com/Uint8Array
 * This is a type-conversion wrapper around `getBody()`
 * @return {!Uint8Array}
 */
proto.root.prototype.getBody_asU8 = function() {
  return /** @type {!Uint8Array} */ (jspb.Message.bytesAsU8(
      this.getBody()));
};


/** @param {!(string|Uint8Array)} value */
proto.root.prototype.setBody = function(value) {
  jspb.Message.setProto3BytesField(this, 2, value);
};


/**
 * optional ext_key_info ext = 3;
 * @return {?proto.ext_key_info}
 */
proto.root.prototype.getExt = function() {
  return /** @type{?proto.ext_key_info} */ (
    jspb.Message.getWrapperField(this, proto.ext_key_info, 3));
};


/** @param {?proto.ext_key_info|undefined} value */
proto.root.prototype.setExt = function(value) {
  jspb.Message.setWrapperField(this, 3, value);
};


proto.root.prototype.clearExt = function() {
  this.setExt(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.root.prototype.hasExt = function() {
  return jspb.Message.getField(this, 3) != null;
};



/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.Ip_info = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.Ip_info, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.Ip_info.displayName = 'proto.Ip_info';
}


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.Ip_info.prototype.toObject = function(opt_includeInstance) {
  return proto.Ip_info.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.Ip_info} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.Ip_info.toObject = function(includeInstance, msg) {
  var f, obj = {
    originIp: jspb.Message.getFieldWithDefault(msg, 1, ""),
    originPort: jspb.Message.getFieldWithDefault(msg, 2, 0),
    observeIp: jspb.Message.getFieldWithDefault(msg, 3, ""),
    observePort: jspb.Message.getFieldWithDefault(msg, 4, 0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.Ip_info}
 */
proto.Ip_info.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.Ip_info;
  return proto.Ip_info.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.Ip_info} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.Ip_info}
 */
proto.Ip_info.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setOriginIp(value);
      break;
    case 2:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setOriginPort(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setObserveIp(value);
      break;
    case 4:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setObservePort(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.Ip_info.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.Ip_info.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.Ip_info} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.Ip_info.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getOriginIp();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getOriginPort();
  if (f !== 0) {
    writer.writeInt32(
      2,
      f
    );
  }
  f = message.getObserveIp();
  if (f.length > 0) {
    writer.writeString(
      3,
      f
    );
  }
  f = message.getObservePort();
  if (f !== 0) {
    writer.writeInt32(
      4,
      f
    );
  }
};


/**
 * optional string origin_ip = 1;
 * @return {string}
 */
proto.Ip_info.prototype.getOriginIp = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/** @param {string} value */
proto.Ip_info.prototype.setOriginIp = function(value) {
  jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional int32 origin_port = 2;
 * @return {number}
 */
proto.Ip_info.prototype.getOriginPort = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 2, 0));
};


/** @param {number} value */
proto.Ip_info.prototype.setOriginPort = function(value) {
  jspb.Message.setProto3IntField(this, 2, value);
};


/**
 * optional string observe_ip = 3;
 * @return {string}
 */
proto.Ip_info.prototype.getObserveIp = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/** @param {string} value */
proto.Ip_info.prototype.setObserveIp = function(value) {
  jspb.Message.setProto3StringField(this, 3, value);
};


/**
 * optional int32 observe_port = 4;
 * @return {number}
 */
proto.Ip_info.prototype.getObservePort = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 4, 0));
};


/** @param {number} value */
proto.Ip_info.prototype.setObservePort = function(value) {
  jspb.Message.setProto3IntField(this, 4, value);
};



/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.user_info = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.user_info, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.user_info.displayName = 'proto.user_info';
}


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.user_info.prototype.toObject = function(opt_includeInstance) {
  return proto.user_info.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.user_info} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.user_info.toObject = function(includeInstance, msg) {
  var f, obj = {
    uid: jspb.Message.getFieldWithDefault(msg, 1, 0),
    nickName: jspb.Message.getFieldWithDefault(msg, 2, ""),
    avartaUrl: jspb.Message.getFieldWithDefault(msg, 3, ""),
    isOnline: jspb.Message.getFieldWithDefault(msg, 4, 0),
    ip: jspb.Message.getFieldWithDefault(msg, 5, ""),
    ipInfo: (f = msg.getIpInfo()) && proto.Ip_info.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.user_info}
 */
proto.user_info.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.user_info;
  return proto.user_info.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.user_info} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.user_info}
 */
proto.user_info.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readUint32());
      msg.setUid(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setNickName(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setAvartaUrl(value);
      break;
    case 4:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setIsOnline(value);
      break;
    case 5:
      var value = /** @type {string} */ (reader.readString());
      msg.setIp(value);
      break;
    case 6:
      var value = new proto.Ip_info;
      reader.readMessage(value,proto.Ip_info.deserializeBinaryFromReader);
      msg.setIpInfo(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.user_info.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.user_info.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.user_info} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.user_info.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getUid();
  if (f !== 0) {
    writer.writeUint32(
      1,
      f
    );
  }
  f = message.getNickName();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getAvartaUrl();
  if (f.length > 0) {
    writer.writeString(
      3,
      f
    );
  }
  f = message.getIsOnline();
  if (f !== 0) {
    writer.writeInt32(
      4,
      f
    );
  }
  f = message.getIp();
  if (f.length > 0) {
    writer.writeString(
      5,
      f
    );
  }
  f = message.getIpInfo();
  if (f != null) {
    writer.writeMessage(
      6,
      f,
      proto.Ip_info.serializeBinaryToWriter
    );
  }
};


/**
 * optional uint32 uid = 1;
 * @return {number}
 */
proto.user_info.prototype.getUid = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/** @param {number} value */
proto.user_info.prototype.setUid = function(value) {
  jspb.Message.setProto3IntField(this, 1, value);
};


/**
 * optional string nick_name = 2;
 * @return {string}
 */
proto.user_info.prototype.getNickName = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/** @param {string} value */
proto.user_info.prototype.setNickName = function(value) {
  jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * optional string avarta_url = 3;
 * @return {string}
 */
proto.user_info.prototype.getAvartaUrl = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/** @param {string} value */
proto.user_info.prototype.setAvartaUrl = function(value) {
  jspb.Message.setProto3StringField(this, 3, value);
};


/**
 * optional int32 is_online = 4;
 * @return {number}
 */
proto.user_info.prototype.getIsOnline = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 4, 0));
};


/** @param {number} value */
proto.user_info.prototype.setIsOnline = function(value) {
  jspb.Message.setProto3IntField(this, 4, value);
};


/**
 * optional string ip = 5;
 * @return {string}
 */
proto.user_info.prototype.getIp = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 5, ""));
};


/** @param {string} value */
proto.user_info.prototype.setIp = function(value) {
  jspb.Message.setProto3StringField(this, 5, value);
};


/**
 * optional Ip_info ip_info = 6;
 * @return {?proto.Ip_info}
 */
proto.user_info.prototype.getIpInfo = function() {
  return /** @type{?proto.Ip_info} */ (
    jspb.Message.getWrapperField(this, proto.Ip_info, 6));
};


/** @param {?proto.Ip_info|undefined} value */
proto.user_info.prototype.setIpInfo = function(value) {
  jspb.Message.setWrapperField(this, 6, value);
};


proto.user_info.prototype.clearIpInfo = function() {
  this.setIpInfo(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.user_info.prototype.hasIpInfo = function() {
  return jspb.Message.getField(this, 6) != null;
};


/**
 * @enum {number}
 */
proto.enum_root_type = {
  ENUM_ROOT_TYPE_REQUEST: 0,
  ENUM_ROOT_TYPE_RESPOND: 2,
  ENUM_ROOT_TYPE_ERROR: 3,
  ENUM_ROOT_TYPE_MESSAGE: 4
};

/**
 * @enum {number}
 */
proto.enum_root_server = {
  ENUM_ROOT_SERVER_LOGIN: 0,
  ENUM_ROOT_SERVER_PING: 2,
  ENUM_ROOT_SERVER_SENT_MSG: 3,
  ENUM_ROOT_SERVER_GROUP_MSG: 4,
  ENUM_ROOT_SERVER_BROADCAST: 5,
  ENUM_ROOT_SERVER_NOTIFICATION: 6
};

/**
 * @enum {number}
 */
proto.enum_server_method = {
  LOGIN: 0,
  LOGOUT: 2,
  SIGNIN: 3,
  SENT_MSG: 10,
  GROUP_MSG: 20,
  BROADCAST: 30,
  NOTIFICATION_ADDFRIEND: 100,
  NOTIFICATION_RECEIVEFRIEND: 102,
  NOTIFICATION_LOGIN_OTHER_DEVICE: 103,
  PING: 256
};

goog.object.extend(exports, proto);
